# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  Tags: /tags
  Categories: /categories
  Contact: /about

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname: uliianblog
  changyan: false

# Google Analytics Tracking ID
google_analytics: UA-123911569-2

# Social Accounts
# twitter_url: https://twitter.com/?lang=en
# facebook_url: https://www.facebook.com/
# instagram_url: https://www.instagram.com/
# dribble_url: https://dribbble.com/
github_url: https://github.com/uliian
# googleplus_url: https://plus.google.com/
# behance_url: https://www.behance.net/
# fivehundredpx_url: https://500px.com/
email_url: yncxcxz@126.com
weibo_url: https://weibo.com
# rss_url: \#

# Footer About Text
footer_about: "ULiian 的个人博客"

# Footer Copyright Line
footer_copyright: "@Uliian. All right reserved | Design & Hexo <a href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"

