language: node_js
node_js:
  - "8"
cache:
  yarn: true
script:
    - hexo deploy
    - chmod +x ./ci/qshell    
    - ./ci/qshell account $qiniuak $qiniusk
    - ./ci/qshell qupload ./ci/qiniuconfig.cfg