language: node_js
node_js:
  - "7"
cache:
  yarn: true
script:
    - hexo deploy
    - ./ci/qshell
    - echo $PWD
    - chmod +x ./ci/qshell    
    - ./ci/qshell account $qiniuak $qiniusk
    - ./ci/qshell qupload ./qiniuconfig.cfg"